class Config:
    EPS = 1e-14
    RPN_CLOBBER_POSITIVES = False
    RPN_NEGATIVE_OVERLAP = 0.3
    RPN_POSITIVE_OVERLAP = 0.7
    RPN_FG_FRACTION = 0.5
    RPN_BATCHSIZE = 300
    RPN_BBOX_INSIDE_WEIGHTS = (1.0, 1.0, 1.0, 1.0)
    RPN_POSITIVE_WEIGHT = -1.0

    RPN_PRE_NMS_TOP_N = 12000
    RPN_POST_NMS_TOP_N = 1000
    RPN_NMS_THRESH = 0.7
    RPN_MIN_SIZE = 8
