name: videoEnv
channels:
  - defaults
  - anaconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
dependencies:
  - python=3.8
  - paddlepaddle-gpu>2.1.3
  - cudatoolkit>=11.2.2
  - ffmpeg
  - spacy>=3.2.1
  - spacy-model-en_core_web_sm>=3.2.0
  - cupy>=9.1.0
  - pip
  - pip:
    - -r requirements_gpu.txt