name: videoEnv
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - ffmpeg
  - spacy>=3.2.1
  - spacy-model-en_core_web_sm==3.2.0
  - pip
  - pip:
    - -r requirements.txt