class Config:
    MAX_HORIZONTAL_GAP = 50
    TEXT_PROPOSALS_MIN_SCORE = 0.7
    TEXT_PROPOSALS_NMS_THRESH = 0.2
    MIN_V_OVERLAPS = 0.7
    MIN_SIZE_SIM = 0.7
    MIN_RATIO = 0.5
    LINE_MIN_SCORE = 0.9
    TEXT_PROPOSALS_WIDTH = 16
    MIN_NUM_PROPOSALS = 2
